version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10.11
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: venv を設定
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            python -m venv helloworld
            . helloworld/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: テストを実行
          command: |
            . helloworld/bin/activate
            python test_hello_world.py
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker イメージをビルドしてプッシュ
          command: |
            . helloworld/bin/activate
            pip install pyinstaller
            pip install --upgrade markupsafe
            pyinstaller -F hello_world.py
            docker build -t ariv3ra/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push ariv3ra/$IMAGE_NAME:$TAG
      - run:
          name: アプリを Docker 経由で Digital Ocean サーバーにデプロイ
          command: |
            ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"
